# OpenAPI version identifier - required for OpenAPI 3.0 domains
openapi: 3.0.0

#######################
# Optional info section
#######################
info:
  title: Dominio de Productos
  description: Dominio de productos para Toures Balon
  version: '1.0.0'

components:

  ####################
  # Common data models
  ####################
  schemas:
  
  ####################
  # Objetos
  ####################
    Producto:
      type: object
      description: paquete que contiene todos los componentes necesarios para un plan
      required:
        - id
      properties:
        id:
          type: number
        descripcion:
          type: string
        fechaCreacion:
          type: string
          format: date-time
        transportes:
          type: array
          items:
            $ref: '#/components/schemas/Transporte'
        eventos:
          type: array
          items:
            $ref: '#/components/schemas/Evento'
        hospedajes:
          type: array
          items:
            $ref: '#/components/schemas/Hospedaje'
    
    Transporte:
      type: object
      description: transportes habilitados para realizar un viaje a cualquier destino
      required: 
        - id
      properties:
        id:
          type: number
          description: id interno del transporte
        description:
          type: string
        vehiculo:
          $ref: '#/components/schemas/Vehiculo'
        fechaPartida:
          type: string
          format: date-time
        lugarPartida:
          $ref: 'https://raw.githubusercontent.com/optimus1006/toures-balon/master/domains/utilitarios/DominioUtilitarios-1.0.0-domain.yaml#/components/schemas/Ciudad'
        fechaLlegada:
          type: string
          format: date-time
        lugarDestino:
          $ref: 'https://raw.githubusercontent.com/optimus1006/toures-balon/master/domains/utilitarios/DominioUtilitarios-1.0.0-domain.yaml#/components/schemas/Ciudad'
        asientos:
          description: indica la cantidad de voletos comprados para el transporte
          type: array
          items:
            $ref: '#/components/schemas/Asiento'
        cantidadCupos:
          description: indica la cantidad de asientos que el convenio esta dispuesto a ofrecer
          type: integer
        estado:
          type: string
          description: >
              'Estado del transporte:'
                * ACTIVO: Activo
                * CANCELADO: Cancelado
                * APLAZADO: Aplazado
          enum: [ACTIVO, CANCELADO, APLAZADO]
        tipo:
          type: string
          description: >
              'tipo de transporte:'
                * VIP: vip
                * TURISTA: Medio
                * ECONOMICO: precio bajo
          enum: [VIP, TURISTA, ECONOMICO]
        valor:
          type: number
          format: currency
        convenio:
            $ref: 'https://raw.githubusercontent.com/optimus1006/toures-balon/master/domains/convenios/DominioConvenios-1.0.0.yaml#/components/schemas/Convenio'
        
    Asiento:
      type: object
      description: Puestos, cillas asociadas a un medio de transporte
      properties:
        id:
          type: integer
          format: int64
        valor:
          description: valor de asignacion del asiento
          type: string
        idCliente:
          $ref: 'https://raw.githubusercontent.com/optimus1006/toures-balon/master/domains/clientes/ClientesDominio-1.0.0.yaml#/components/schemas/Cliente'
        fechaReserva:
          type: string
          format: date-time
            
    Vehiculo:
      type: object
      description: tipos de vehiculos para transportarse de un lugar a otro
      properties:
        id:
          type: string
        tipoVehiculo:
          $ref: '#/components/schemas/TipoTransporte'
        marca:
          type: string
        modelo:
          type: integer
          format: int32
        referencia:
          type: string
          
    Hospedaje:
      type: object
      description: Contiene la información del sitio donde se hospedará un cliente que pagó por una habitación en un hotel.
      properties:
        codigo:
          description: Código que identifica al hospedaje
          type: integer
          format: int64
        nombre:
          description: Nombre del establecimiento de hospedaje.
          maxLength: 255
          type: string
          example: 'HOTEL DUERME BUENO'
        tipoHospedaje:
          $ref: '#/components/schemas/TipoHospedaje'
        calificacion:
          description: Calificación del hotel según los clientes y/o expertos.
          type: integer
          format: int32
          minimum: 0
          maximum: 5
        direccion:
          description: Código del producto dentro del sistema.
          maxLength: 255
          type: string
          example: '23TH ST - CRAWROFD - 76005'
        geolocalizacion:
          $ref: '#/components/schemas/UbicacionGeografica'
        ciudad:
          $ref: 'https://raw.githubusercontent.com/optimus1006/toures-balon/master/domains/utilitarios/DominioUtilitarios-1.0.0-domain.yaml#/components/schemas/Ciudad'
        informacion:
          description: Texto que contiene una descripción del sitio, sus servicios, ventajas, etc.
          type: string
          maxLength: 4000
        cantidadCuartos:
          description: Cantidad de cuartos disponibles en el hotel.
          type: integer
          format: int32
          minimum: 0
        fotos:
          description: lista de fotos que muestran las instalaciones del hospedaje.
          type: array
          items:
            $ref: '#/components/schemas/Imagen'
        cuartos:
          description: lista de cuartos que tienen las instalaciones del hospedaje.
          type: array
          items:
            $ref: '#/components/schemas/Cuarto'
        convenio:
            $ref: 'https://raw.githubusercontent.com/optimus1006/toures-balon/master/domains/convenios/DominioConvenios-1.0.0.yaml#/components/schemas/Convenio'
            
    Cuarto:
      description: Espacio, habitacion o lugar que pertenece a un hospedaje
      type: object
      properties:
        id:
          description: identificador unico del cuarto
          type: integer
          format: int64
        numeroCuarto:
          description: identificador unico del cuarto en el hospedaje
          type: string
        Cliente:
          $ref: 'https://raw.githubusercontent.com/optimus1006/toures-balon/master/domains/clientes/ClientesDominio-1.0.0.yaml#/components/schemas/Cliente'
        fechaReservaInicio:
          description: fecha de inicio de la reserva del cuarto
          type: string
          format: date-time
        fechaReservaFin:
          description: fecha de fin de la reserva del cuarto
          type: string
          format: date-time
        fechaReserva:
          description: fecha en que fue realizada la reserva
          type: string
          format: date-time
        valorCuarto:
          description: valor de reserva por noche del cuarto
          type: string
          format: currency

    UbicacionGeografica: 
      description: Ubicación geográfica de un sitio, definido por coordenadas polares (latitud y longitud).
      type: object
      properties: 
        latitud: 
          description: Coordenada de latitud.
          type: number
          format: float
        longitud: 
          description: Coordenada de longitud.
          type: number
          format: float
          
    TipoHospedaje:
      description: Tipos de hotel posibles.
      type: string
      enum: 
        - HOTEL
        - MOTEL
        - RESORT
        - VILLA
        - CABAÑA
        
    Imagen: 
      description: Contiene la información de la imagen que se mostrará del evento.
      type: object
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
        path:
          type: string
        dimensiones:
          type: object
          properties:
            ancho:
              type: integer
              format: int64
              minimum: 1
            alto: 
              type: integer
              format: int64
              minimum: 1
        data:
          type: string
          format: binary
          
    Evento: 
      description: Contiene la información del evento al cual es cliente asistirá.
      type: object
      properties:
        id: 
          type: integer
          format: int64
        nombre:
          type: string
          maxLength: 100
        descripcion:
          type: string
          maxLength: 255
        fecha:
          type: string
          format: date
        hora:
          type: string
          format: time
        zonaHoraria:
          type: string
        cantidad: 
          type: integer
        ubicacionEvento: 
          $ref: '#/components/schemas/Direccion'
        localidades: 
          type: array
          items:
            $ref: '#/components/schemas/Localidad'
        tipo:
          type: string
          description: Tipo de evento.
          enum:
            - Concierto
            - Futbol
            - Baloncesto
            - Actividad
            - Otro
        imagenes: 
          type: array
          items:
            $ref: '#/components/schemas/Imagen'
        imagenPrincipal:
          type: integer
          format: int32
          default: 1
        estado:
          type: string
          description: Estado el evento
          enum:
            - ACTIVO
            - INACTIVO
            
    Localidad: 
      description: Contiene la información de la localidad dentro del evento, en caso de existir .
      type: object
      properties:
        id: 
          type: integer
          readOnly: true
        nombre:
          type: string
        precio:
          type: number
          format: double
        aforo:
          type: integer
        asientos:
          description: indica la cantidad de voletos comprados para el evento
          type: array
          items:
            $ref: '#/components/schemas/Asiento'
          
    Direccion: 
      description: Contiene la información de la direccion
      type: object
      properties:
        direccion:
          description: Dirección completa.
          maxLength: 254
          type: string
        ubicacion:
            $ref: '#/components/schemas/UbicacionGeografica'
        tipo:
          type: string
          enum:
            - CASA
            - OFICINA
            - OTRO
        pais:
          $ref: 'https://raw.githubusercontent.com/optimus1006/toures-balon/master/domains/utilitarios/DominioUtilitarios-1.0.0-domain.yaml#/components/schemas/Pais'
        ciudad:
          $ref: 'https://raw.githubusercontent.com/optimus1006/toures-balon/master/domains/utilitarios/DominioUtilitarios-1.0.0-domain.yaml#/components/schemas/Ciudad'
        estado:
          $ref: '#/components/schemas/Estado'
        fechaCreacion:
          description: Fecha de creación de la dirección
          type: string
          format: date-time
          
    
  ####################
  # Catalogos
  ####################
    TipoTransporte:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        description:
          type: string
        capacidadPersonas:
          type: number
        capacidadEquipaje:
          type: number
        tipoCapacidadCarga:
          type: string
          description: >
            'Capacidad:'
              * Kg: Kilogramos
              * Ton: Toneladas
          enum: [Kg, Ton]
          
    ErrorResponse:
      description: Respuesta de la operación de un servicio.
      properties:
        message:
          maxLength: 500
          minLength: 1
          type: string
          description: Descripción del error general.
        error:
          type: array
          description: Lista de los errores específicos.
          items:
            $ref: '#/components/schemas/Error'
            
    Estado:
      description: Estado
      type: object
      properties:
        codigo: 
          description: Código del estado.
          format: int32
          minimum: 1
          type: number
        nombre: 
          description: Nombre del estado.
          type: string
          minLength: 1
          maxLength: 64
        pais:
          $ref: 'https://raw.githubusercontent.com/optimus1006/toures-balon/master/domains/utilitarios/DominioUtilitarios-1.0.0-domain.yaml#/components/schemas/Pais'
            
    Error:
      properties:
        code:
          maxLength: 128
          minLength: 1
          type: string
          description: Código específico del error.
        id:
          maxLength: 40
          minLength: 1
          type: string
          description: Id de referencia única para propósitos de auditoría.
        message:
          maxLength: 500
          minLength: 1
          type: string
          description: Descripción del error específico.
        path:
          maxLength: 500
          minLength: 1
          type: string
          description: Al referirse de un error debido a un campo específico, se describe la ruta del campo.
        url:
          maxLength: 500
          minLength: 1
          type: string
          description: URL de la documentación en donde se encuentra mayor información sobre el error.
      description: Error específico que describe un problema presentado al ejecutar una operación.
    ErrorResponseDetail:
      required:
      - error
      - message
      properties:
        message:
          maxLength: 500
          minLength: 1
          type: string
          description: Descripción del error general.
        error:
          required:
          - code
          - message
          type: array
          description: Lista de los errores específicos.
          items:
            $ref: '#/components/schemas/Error'
      description: Mensaje de respuesta de error